import User from '../models/User.js';
import Shipment from '../models/Shipment.js';
import crypto from 'crypto';
import sendEmail from '../utils/email.js';

// Helper function to simulate staff performance data
const getStaffPerformance = async (staffId) => {
  const assignedShipments = await Shipment.countDocuments({ agent: staffId });
  // Simulate rating for now, in a real app this would be calculated from feedback
  const rating = (assignedShipments % 5) + 3.5; // Example: 3.5 to 4.9
  return { assignedShipments, rating: parseFloat(rating.toFixed(1)) };
};

// @desc    Get all staff with pagination, search, and filtering
// @route   GET /api/staff
// @access  Private/Admin
export const getStaff = async (req, res) => {
  try {
    const page = parseInt(req.query.page) || 1;
    const limit = parseInt(req.query.limit) || 10;
    const search = req.query.search || '';
    const statusFilter = req.query.status || 'All';
    const roleFilter = req.query.role || 'All';

    const query = { role: 'staff' };

    if (search) {
      query.$or = [
        { name: { $regex: search, $options: 'i' } },
        { email: { $regex: search, $options: 'i' } },
        { location: { $regex: search, $options: 'i' } }, // Search by region/location
      ];
    }

    if (statusFilter && statusFilter !== 'All') {
      query.status = statusFilter;
    }

    if (roleFilter && roleFilter !== 'All') {
      query.role = roleFilter;
    }

    const staff = await User.find(query)
      .select('-password')
      .sort({ createdAt: -1 })
      .skip((page - 1) * limit)
      .limit(limit);

    const total = await User.countDocuments(query);

    const staffWithPerformance = await Promise.all(
      staff.map(async (staff) => {
        const performance = await getStaffPerformance(staff._id);
        return { ...staff.toObject(), ...performance };
      })
    );

    res.status(200).json({
      status: 'success',
      data: {
        staff: staffWithPerformance,
        pagination: {
          total,
          page,
          limit,
          totalPages: Math.ceil(total / limit),
        },
      },
    });
  } catch (error) {
    res.status(500).json({ status: 'error', message: error.message });
  }
};

// @desc    Get staff summary statistics
// @route   GET /api/staff/summary
// @access  Private/Admin
export const getStaffSummary = async (req, res) => {
  try {
    const totalAgents = await User.countDocuments({ role: 'staff' });
    const activeOnDelivery = await User.countDocuments({ role: 'staff', status: 'Active' });
    const suspended = await User.countDocuments({ role: 'staff', status: 'Inactive' });

    const rolesBreakdown = await User.aggregate([
      { $match: { role: { $in: ['admin', 'staff'] } } },
      { $group: { _id: '$role', count: { $sum: 1 } } },
      { $project: { name: '$_id', value: '$count' } }
    ]);

    res.status(200).json({
      status: 'success',
      data: {
        totalAgents,
        activeOnDelivery,
        suspended,
        rolesBreakdown,
      },
    });
  } catch (error) {
    res.status(500).json({ status: 'error', message: error.message });
  }
};

// @desc    Create a new staff member
// @route   POST /api/staff
// @access  Private/Admin
export const createStaff = async (req, res) => {
  try {
    let { name, email, password, phone, role, status, profilePicture, branch } = req.body;

    // Check if user already exists
    const userExists = await User.findOne({ email });
    if (userExists) {
      return res.status(400).json({ status: 'fail', message: 'Staff member with this email already exists' });
    }

    let autoGeneratedPassword = '';
    if (!password) {
      autoGeneratedPassword = crypto.randomBytes(8).toString('hex');
      password = autoGeneratedPassword;
    }

    const staffMember = await User.create({
      name,
      email,
      password,
      phone,
      role,
      status,
      profilePicture,
      branch,
    });

    // If password was auto-generated, send it via email
    if (autoGeneratedPassword) {
      try {
        await sendEmail({
          to: email,
          subject: 'Your BongoExpress Account Credentials',
          text: `Welcome to the team! Your account has been created.\n\nEmail: ${email}\nPassword: ${autoGeneratedPassword}\n\nPlease log in and change your password immediately.`,
        });
      } catch (emailError) {
        console.error("Failed to send welcome email:", emailError);
        // Don't fail the whole request, but maybe log this for the admin
      }
    }

    staffMember.password = undefined;

    res.status(201).json({ status: 'success', data: { staff: staffMember } });
  } catch (error) {
    res.status(400).json({ status: 'fail', message: error.message });
  }
};

// @desc    Update a staff member
// @route   PUT /api/staff/:id
// @access  Private/Admin
export const updateStaff = async (req, res) => {
  try {
    const { name, email, phone, role, status, profilePicture, branch } = req.body;

    // Exclude role and password from being updated through this endpoint
    const staffMember = await User.findByIdAndUpdate(
      req.params.id,
      { name, email, phone, role, status, profilePicture, branch },
      { new: true, runValidators: true }
    ).select('-password');

    if (!staffMember) {
      return res.status(404).json({ status: 'fail', message: 'No staff member found with that ID' });
    }

    res.status(200).json({ status: 'success', data: { staff: staffMember } });
  } catch (error) {
    res.status(400).json({ status: 'fail', message: error.message });
  }
};

// @desc    Delete a staff member
// @route   DELETE /api/staff/:id
// @access  Private/Admin
export const deleteStaff = async (req, res) => {
  try {
    const staffMember = await User.findById(req.params.id);

    if (!staffMember || staffMember.role !== 'staff') {
      return res.status(404).json({ status: 'fail', message: 'No staff member found with that ID' });
    }

    // For now, we'll just delete the user.
    await User.findByIdAndDelete(req.params.id);

    res.status(204).json({ status: 'success', data: null });
  } catch (error) {
    res.status(400).json({ status: 'fail', message: error.message });
  }
};

// @desc    Get a list of all staff for dropdowns
// @route   GET /api/staff/list
// @access  Private/Admin
export const getStaffList = async (req, res) => {
  try {
    const staff = await User.find({ role: 'staff' }).select('name');
    res.status(200).json({
      status: 'success',
      data: { staff },
    });
  } catch (error) {
    res.status(500).json({ status: 'error', message: error.message });
  }
};